### ISSUE TITLE
Broken phpseclib/phpseclib dependency

### ISSUE THREAD

**Issue by jaimeperez** [gree/jose#24]
Hi!

The dependency on [phpseclib/phpseclib](https://github.com/phpseclib/phpseclib) is broken. They have just released 1.0.0 (which is fine), but also 2.0.0, which introduces namespaces and therefore breaks the `jose` library as it doesn't use namespaces for this dependency.

We've tested with 1.0.0 and it apparently works fine, so I would suggest changing the dependency to (but you may want to check that actually **everything** is working for you):

```json
    "phpseclib/phpseclib": ">=0.3.5 <2.0.0"
```

I'd say it's quite urgent, since at the moment the library is completely broken for new installations.

Thanks!

**Comment by nov** [comment]
OK, I'll release it's probably good timing to remove php5.2 support and use phpseclib 2.0+

**Comment by nov** [comment]
https://github.com/gree/jose/pull/26

**Comment by jaimeperez** [comment]
Good that you were able to spot the problem with 1.0.0. Thanks for solving this, Nov!
